# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 395b322d07cf5995cd38649e7d03a5e3c61f2144c57ae48b8d74e82be9a30be1124d969d90c42f762a446a3144fd5c90f0e7be99a163bda7b60a2a52234da49e

test:
  secret_key_base: 47c7f0994b34e29059fbe579a8ce597eebe9eb5f5eebf4ff177ef55cfb17ba662c545c79d91326ec8f266feed4154d8fea71e7f5fba3ccb94a9dfdc3f42514c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
